Sheepdog: fix command execution failure
Sheepdog driver uses oslo_concurrency.processutils.execute
to execute the collie command.
Until the commit 79532ea599cd0226e7176c6c7d59e04ee3b1a8ff,
the driver uses execute in shell=True mode. In this mode,
the arguments of execute can be a string of command arguments.
But in default shell=False mode, the arguments of execute
should be a sequence of command arguments.

A minimum example:

>>> processutils.execute('echo hoge', shell=True)
('hoge\n', '')

>>> processutils.execute('echo hoge')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/
         oslo_concurrency/processutils.py", line 363, in execute
    env=env_variables)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py",
    line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

>>> processutils.execute('echo', 'hoge')
('hoge\n', '')

Change-Id: I73c3f071f28ee5c7f5d8f7a692a233fbd19f9260
Closes-Bug: #1620214